version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: telegram_storage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  telegram-storage:
    image: telegram-storage:latest
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=telegram_storage;Username=postgres;Password=password
      - ASPNETCORE_SERVER_KESTREL__LIMITS__MAXREQUESTBODYSIZE=-1
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: